spring:
  application:
    name: nextxi-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/nextxi?currentSchema=public
    username: nextxi
    password: nextxi

  flyway:
    schemas:
      - public
    default-schema: public
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    repair-on-migrate: true
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
